ALTER TABLE products ADD COLUMN IF NOT EXISTS specification VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS feature1 VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS feature2 VARCHAR(100);
